# Site settings
title: Bao Jie's Blog
notes_title: "Bao Jie's Reading Notes"
SEOTitle: 鲍捷的博客 | Bao Jie's Blog
header-img: 
tagline: ''
sidebar_image: 
lang: 'zh-cmn-Hans'
url: http://www.jiebaojie.com/
author: Bao Jie
plus: 
description: "鲍捷的博客"
keyword: "鲍捷的博客"

# Build settings
markdown: kramdown
highlighter: rouge
baseurl: # the subpath of your site, e.g. /blog/

permalink:   /:categories/:title/
paginate: 8
paginate_path: "/page:num/"

highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Duoshuo settings
duoshuo_username: Bao Jie
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我本科和研究生毕业于同济大学，目前就职于百度——程序化广告部，从事研发工作。关注后端Web技术，大数据技术，广告系统技术等。"
sidebar-avatar:     # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

# SNS settings
github_username: jiebaojie

# Friends
friends: [
    {
        title: "neo时刻准备着",
        href: "http://neoremind.com"
    },{
        title: "Ray's Blog",
        href: "http://www.predatorray.me/"
    },{
        title: "Yin Haomin's Blog",
        href: "http://www.yinhaomin.com/"
    },{
        title: "Knight's Blog",
        href: "http://www.liaoqiqi.com/"
    }
]
